=== zhujiancom/BillSystem/src/main/java/org/zj/framework/authorization/tools/config/modules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
			targetNamespace="http://www.renters.modules" elementFormDefault="qualified">
	<element name="modules">
		<complexType>
			<sequence>
				<element name="action">
					<simpleType>
						<restriction base="string">
							<enumeration value="CREATE"/>
							<enumeration value="UPDATE"/>
						</restriction>
					</simpleType>
				</element>
				<element name="module" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="name" type="string"/>
						<element name="code" type="string"/>
						<element name="url" type="string"/>
					</sequence>
				</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== zhujiancom/BillSystem/src/main/java/org/zj/framework/authorization/tools/config/modules.xml
<?xml version="1.0" encoding="UTF-8"?>
<modules
	xmlns="http://www.renters.modules"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.renters.modules modules.xsd">
	<action>UPDATE</action>
	<module>
		<name>用户管理</name>
		<code>m_001</code>
		<url></url>
	</module>
	<module>
		<name>用户管理</name>
		<code>m_001</code>
		<url></url>
	</module>
	<module>
		<name>用户管理</name>
		<code>m_001</code>
		<url></url>
	</module>
	<module>
		<name>用户管理</name>
		<code>m_001</code>
		<url></url>
	</module>
</modules>
